# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://github.com/JAMK-IT/TTVW0110-challenge-factory/wiki
title: JAMK's Challenge Factory
email: your-email@domain.com
author: JAMK-IT
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2016. &nbsp; Project maintained by JAMK-IT. &nbsp; Hosted on GitHub Pages.'
credits: 'Credits: Open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: wiki
    url: https://github.com/JAMK-IT/TTVW0110-challenge-factory/wiki
    icon: fa fa-github fa-fw
  - title: code
    url: https://github.com/JAMK-IT/TTVW0110-challenge-factory/
    icon: fa fa-file fa-fw
